spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/safetylinetest
    username: safetyline
    password: 19980223x
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/safetyline
#    username: root
#    password: 19980223x
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true